//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMasterDetailFaculty.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Faculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty()
        {
            this.Students = new HashSet<Student>();
        }

        public int ID { get; set; }
        [Required]
        public string FacultyName { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        [Required]
        public string CourseName { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime CourseStartDate { get; set; }
        [DisplayName("Picture")]
        public string PicPath { get; set; }
        [NotMapped]
        public HttpPostedFileBase Picture { get; set; }
        public bool IsRunning { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
